name: ong_music
description: Jonathan Ong's music content.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  csv: ^5.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  http: ^1.1.2
  logger: ^2.0.2+1
  logging: ^1.2.0
  path: ^1.8.2
  shared_preferences: ^2.2.2
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  sqflite_common_ffi_web: ^0.4.2+2
  url_launcher: ^6.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/ongLit.png
    - assets/ongZoom.png

# "dart run flutter_launcher_icons" to regenerate icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ongZoom.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/ongZoom.png"
    background_color: "#000"
    theme_color: "#000"
  windows:
    generate: true
    image_path: "assets/ongZoom.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/ongZoom.png"
