name: flutter_ong_log
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  csv: ^5.1.1
  flutter:
    sdk: flutter
  http: ^0.13.6
  logger: ^2.0.2+1
  logging: ^1.2.0
  path: ^1.8.2
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
