name: Flutter CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        #flutter-version: '3.7.7'
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build apk
    - uses: actions/upload-artifact@v4
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-release.apk
    - run: flutter build appbundle
    - uses: actions/upload-artifact@v4
      with:
        name: aab
        path: build/app/outputs/bundle/release/app-release.aab
    - run: flutter build web
